################################# Default configuration ###################
baseURL = "https://vivumlab.com"
title = "VivumLab"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []
publishDir = "docs"

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "About"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "Services"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "Getting Started"
url = "#contact"
weight = 3

[[Languages.en.menu.main]]
name = "Documentation"
url = "https://docs.vivumlab.com/"
weight = 4

################### Spanish Navigation ########################
[[Languages.es.menu.main]]
name = "Sobre"
url = "#about"
weight = 1

[[Languages.es.menu.main]]
name = "Los servicios"
url = "#services"
weight = 2

[[Languages.es.menu.main]]
name = "Empezando"
url = "#contact"
weight = 3

[[Languages.es.menu.main]]
name = "Documentación"
url = "https://docs.vivumlab.com/"
weight = 4

################### French Navigation ########################
[[Languages.fr.menu.main]]
name = "Sur"
url = "#about"
weight = 1

[[Languages.fr.menu.main]]
name = "Un Service"
url = "#services"
weight = 2

[[Languages.fr.menu.main]]
name = "Commencer"
url = "#contact"
weight = 3

[[Languages.fr.menu.main]]
name = "Documentation"
url = "https://docs.vivumlab.com/"
weight = 4

################### German Navigation ########################
[[Languages.de.menu.main]]
name = "Um"
url = "#about"
weight = 1

[[Languages.de.menu.main]]
name = "Dienstleistungen"
url = "#services"
weight = 2

[[Languages.de.menu.main]]
name = "Einstieg"
url = "#contact"
weight = 3

[[Languages.de.menu.main]]
name = "Dokumentation"
url = "https://docs.vivumlab.com/"
weight = 4

################### Portuguese Navigation ########################
[[Languages.pt.menu.main]]
name = "Sobre"
url = "#about"
weight = 1

[[Languages.pt.menu.main]]
name = "Os serviços"
url = "#services"
weight = 2

[[Languages.pt.menu.main]]
name = "Começando"
url = "#contact"
weight = 3

[[Languages.pt.menu.main]]
name = "Documentação"
url = "https://docs.vivumlab.com/"
weight = 4

################### Esperanto Navigation ########################
[[Languages.eo.menu.main]]
name = "Pri"
url = "#about"
weight = 1

[[Languages.eo.menu.main]]
name = "Servoj"
url = "#services"
weight = 2

[[Languages.eo.menu.main]]
name = "Komencante"
url = "#contact"
weight = 3

[[Languages.eo.menu.main]]
name = "Dokumentado"
url = "https://docs.vivumlab.com/"
weight = 4

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Deployment to your own infrastructure. Made Easy"
author = "VivumLab"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

############################# social icons ##########################
[[params.social]] # GitHub
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/VivumLab/VivumLab"

[[params.social]] # Discord
icon = "ti-headphone-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://discord.gg/invite/CfXueRYTHJ"

[[params.social]] # Mastodon
icon = "ti-user" # themify icon pack : https://themify.me/themify-icons
link = "https://fosstodon.org/@vivumlab"

[[params.social]] # VivumLab Documentation
icon = "ti-help" # themify icon pack : https://themify.me/themify-icons
link = "https://docs.vivumlab.com/"

################################ English Language ########################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "VivumLab: 2022. Site powered by [Hugo](https://gohugo.io/) & [ThemeFisher](https://github.com/themefisher)"

################################ Spanish Language ########################
[Languages.es]
languageName = "Español"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 2
home = "Inicio"
copyright = "VivumLab: 2022. Sitio web impulsado por [Hugo](https://gohugo.io/) & [ThemeFisher](https://github.com/themefisher)"

################################ French Language ########################
[Languages.fr]
languageName = "Français"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 3
home = "Accueil"
copyright = "VivumLab: 2022. Site Web, propulsé par [Hugo](https://gohugo.io/) & [ThemeFisher](https://github.com/themefisher)"

################################ German Language ########################
[Languages.de]
languageName = "Deutsch"
languageCode = "de-de"
contentDir = "content/german"
weight = 4
home = "Heim"
copyright = "VivumLab: 2022. Website betrieben von [Hugo](https://gohugo.io/) & [ThemeFisher](https://github.com/themefisher)"

################################ Portuguese Language ########################
[Languages.pt]
languageName = "Português"
languageCode = "pt-pt"
contentDir = "content/portuguese"
weight = 5
home = "Começo"
copyright = "VivumLab: 2022. Site, alimentado por [Hugo](https://gohugo.io/) & [ThemeFisher](https://github.com/themefisher)"

################################ Esperanto Language ########################
[Languages.eo]
languageName = "Esperanto"
languageCode = "eo-eo"
contentDir = "content/esperanto"
weight = 6
home = "Hejmo"
copyright = "VivumLab: 2022. Retpaĝon, propulsita de [Hugo](https://gohugo.io/) & [ThemeFisher](https://github.com/themefisher)"
