################################# Default configuration ###################
baseURL = "https://vivumlab.com"
title = "VivumLab"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []
publishDir = "docs"

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "about"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "services"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "contact"
url = "#contact"
weight = 3


################### French Navigation ########################
[[Languages.fr.menu.main]]
name = "sur"
url = "#about"
weight = 1

[[Languages.fr.menu.main]]
name = "un service"
url = "#services"
weight = 2

[[Languages.fr.menu.main]]
name = "contact"
url = "#contact"
weight = 3


################### Spanish Navigation ########################
[[Languages.es.menu.main]]
name = "sobre"
url = "#about"
weight = 1

[[Languages.es.menu.main]]
name = "los servicios"
url = "#services"
weight = 2

[[Languages.es.menu.main]]
name = "contacto"
url = "#contact"
weight = 3


################### Portuguese Navigation ########################
[[Languages.pt.menu.main]]
name = "sobre"
url = "#about"
weight = 1

[[Languages.pt.menu.main]]
name = "os serviços"
url = "#services"
weight = 2

[[Languages.pt.menu.main]]
name = "contato"
url = "#contact"
weight = 3


############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Responsive Multipurpose Parallax Hugo Template"
author = "Themefisher"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

############################# social icons ##########################
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-world" # themify icon pack : https://themify.me/themify-icons
link = "#" # mastodon

[[params.social]]
icon = "ti-game" # themify icon pack : https://themify.me/themify-icons
link = "#" # Discord

[[params.social]]
icon = "ti-ink-pen" # themify icon pack : https://themify.me/themify-icons
link = "#" # Matrix

[[params.social]]
icon = "ti-pencil" # themify icon pack : https://themify.me/themify-icons
link = "#" # Zulip

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "VivumLab: 2022. Site powered by [Hugo](https://gohugo.io/) & [ThemeFisher](https://github.com/themefisher)"

################################ French Language ########################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
copyright = "VivumLab: 2022. Site Web, propulsé par [Hugo](https://gohugo.io/) & [ThemeFisher](https://github.com/themefisher)"

################################ Spanish Language ########################
[Languages.es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 3
home = "Inicio"
copyright = "VivumLab: 2022. Sitio web impulsado por [Hugo](https://gohugo.io/) & [ThemeFisher](https://github.com/themefisher)"

################################ Portuguese Language ########################
[Languages.pt]
languageName = "Pt"
languageCode = "pt-pt"
contentDir = "content/portuguese"
weight = 4
home = "Começo"
copyright = "VivumLab: 2022. Site, alimentado por [Hugo](https://gohugo.io/) & [ThemeFisher](https://github.com/themefisher)"
